### ISSUE TITLE
out of sync in MP

### ISSUE THREAD

**Issue by danielsoftwaree** [SchwarzKruppzo/StierlitzWargame#1]
In the game Men of War: Assault Squad 2 I am trying to get the maximum accuracy function (no spread).

But I get an error out of sync. In the logs is created "SNAPSHOT" which shows the difference crc (Cyclic redundancy check) of the two players (me and the other player)

player 1:
```
[28.06.2023 21.58], v.3.262.1, battle_zones:multi/3v3_russian_hutor:battle_zones, m:0, q:922041
######## SNAPSHOT BEGIN ########
crc:-1561543299 , crc2:-1522318736 , quant:921753
<BD12DF2F> eScene.cpp(933) eQuant::Current().GetPureValue() = 921753
<31A41D71> eScene.cpp(934) Scene::Manager()->Difficulty() = 'multiplayer'
<C5303674> eScene.cpp(935) Scene::fog.Type() {len=4, data='01000000'}
<080F8DB9> eScene.cpp(938) fpu_state = 589855
...
```
player 2:
```
[28.06.2023 21.58], v.3.262.1, battle_zones:multi/3v3_russian_hutor:battle_zones, m:1, q:922041
######## SNAPSHOT BEGIN ########
crc:-1082056329 , crc2:-251629898 , quant:921753
<BD12DF2F> eScene.cpp(933) eQuant::Current().GetPureValue() = 921753
<31A41D71> eScene.cpp(934) Scene::Manager()->Difficulty() = 'multiplayer'
<C5303674> eScene.cpp(935) Scene::fog.Type() {len=4, data='01000000'}
<080F8DB9> eScene.cpp(938) fpu_state = 589855
...
```

I change the values of accuracy, which I found in the game files. They are loaded at startup and checked if there were changes (not allowed to play in the multiplayer, if the data in these files have changed)
```
{level "lvl_1"
    {stand
      {accuracy 1.00}
    }
    {squat
      {accuracy 1.20}
    }
    {crawl
      {accuracy 1.40}
    }
    {cover
      {accuracy 1.50}
    }
    {vehicle
      {accuracy 2.00}
    }
  }
```

But the error is triggered only when shooting. And it depends on the value. If the default value is 1.25, and I change it to 2, the synchronization error does not occur immediately. If the value is 5, it is instantaneous.

Help me please understand how to get around this error

**Comment by SchwarzKruppzo** [comment]
You can't change any of game resource data such as accuracy or speed of vehicles. It will always cause Out of Sync because the whole game is simulated locally on each client. (like in Paradox Interactive games such as Europa Universalis 4)
Difference in values causes another "result" of your game state.

**Comment by danielsoftwaree** [comment]
Thank you very much for the answer
